export interface LoteriaCard {
    id: number;
    name: string;
    image: string;
}

export const LOTERIA_CARDS: LoteriaCard[] = [
    { id: 1, name: "El Gallo", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/1.jpg" },
    { id: 2, name: "El Diablito", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/2.jpg" },
    { id: 3, name: "La Dama", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/3.jpg" },
    { id: 4, name: "El Catrín", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/4.jpg" },
    { id: 5, name: "El Paraguas", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/5.jpg" },
    { id: 6, name: "La Sirena", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/6.jpg" },
    { id: 7, name: "La Escalera", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/7.jpg" },
    { id: 8, name: "La Botella", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/8.jpg" },
    { id: 9, name: "El Barril", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/9.jpg" },
    { id: 10, name: "El Árbol", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/10.jpg" },
    { id: 11, name: "El Melón", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/11.jpg" },
    { id: 12, name: "El Valiente", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/12.jpg" },
    { id: 13, name: "El Gorrito", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/13.jpg" },
    { id: 14, name: "La Muerte", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/14.jpg" },
    { id: 15, name: "La Pera", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/15.jpg" },
    { id: 16, name: "La Bandera", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/16.jpg" },
    { id: 17, name: "El Bandolón", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/17.jpg" },
    { id: 18, name: "El Violoncello", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/18.jpg" },
    { id: 19, name: "La Garza", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/19.jpg" },
    { id: 20, name: "El Pájaro", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/20.jpg" },
    { id: 21, name: "La Mano", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/21.jpg" },
    { id: 22, name: "La Bota", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/22.jpg" },
    { id: 23, name: "La Luna", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/23.jpg" },
    { id: 24, name: "El Cotorro", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/24.jpg" },
    { id: 25, name: "El Borracho", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/25.jpg" },
    { id: 26, name: "El Negrito", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/26.jpg" },
    { id: 27, name: "El Corazón", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/27.jpg" },
    { id: 28, name: "La Sandía", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/28.jpg" },
    { id: 29, name: "El Tambor", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/29.jpg" },
    { id: 30, name: "El Camarón", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/30.jpg" },
    { id: 31, name: "Las Jaras", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/31.jpg" },
    { id: 32, name: "El Músico", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/32.jpg" },
    { id: 33, name: "La Araña", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/33.jpg" },
    { id: 34, name: "El Soldado", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/34.jpg" },
    { id: 35, name: "La Estrella", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/35.jpg" },
    { id: 36, name: "El Cazo", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/36.jpg" },
    { id: 37, name: "El Mundo", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/37.jpg" },
    { id: 38, name: "El Apache", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/38.jpg" },
    { id: 39, name: "El Nopal", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/39.jpg" },
    { id: 40, name: "El Alacrán", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/40.jpg" },
    { id: 41, name: "La Rosa", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/41.jpg" },
    { id: 42, name: "La Calavera", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/42.jpg" },
    { id: 43, name: "La Campana", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/43.jpg" },
    { id: 44, name: "El Cantarito", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/44.jpg" },
    { id: 45, name: "El Venado", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/45.jpg" },
    { id: 46, name: "El Sol", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/46.jpg" },
    { id: 47, name: "La Corona", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/47.jpg" },
    { id: 48, name: "La Chalupa", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/48.jpg" },
    { id: 49, name: "El Pino", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/49.jpg" },
    { id: 50, name: "El Pescado", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/50.jpg" },
    { id: 51, name: "La Palma", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/51.jpg" },
    { id: 52, name: "La Maceta", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/52.jpg" },
    { id: 53, name: "El Arpa", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/53.jpg" },
    { id: 54, name: "La Rana", image: "https://raw.githubusercontent.com/antigravity/loteria-assets/main/54.jpg" },
];
